dist: trusty
language: cpp
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-7
      - g++-7

install:
  - mkdir ~/googletest
  - pushd ~/googletest
  - wget -qO - https://github.com/google/googletest/archive/release-1.8.0.tar.gz | tar -xz
  - cmake -D CMAKE_INSTALL_PREFIX:PATH=$HOME/googletest -D CMAKE_BUILD_TYPE=Release googletest-release-1.8.0
  - make install
  - popd

script:
  - export CC=gcc-7
  - export CXX=g++-7
  - mkdir build
  - cd build
  - cmake -D GTEST_ROOT:PATH=$HOME/googletest ..
  - make
  - make test

notifications:
  email: false