sudo: required
language: cpp
compiler: gcc
dist: trusty

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install:
  - sudo apt-get install -qq g++-8
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-8 90
  - mkdir ~/googletest
  - pushd ~/googletest
  - wget -qO - https://github.com/google/googletest/archive/release-1.8.0.tar.gz | tar -xz
  - cmake -D CMAKE_INSTALL_PREFIX:PATH=$HOME/googletest -D CMAKE_BUILD_TYPE=Release googletest-release-1.8.0
  - make install
  - popd

script:
  - mkdir build
  - cd build
  - cmake -D GTEST_ROOT:PATH=$HOME/googletest ..
  - make
  - make test

notifications:
  email: false