dist: trusty
language: cpp
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-7
      - g++-7

install:
  - mkdir ~/googletest
  - pushd ~/googletest
  - wget -qO - https://github.com/google/googletest/archive/release-1.8.0.tar.gz | tar -xz
  - cd googletest-release-1.8.0/
  - mkdir gtest_build
  - cd gtest_build
  - cmake ../
  - make
  - cp -r ../include/gtest /usr/local/include
  - cp lib*.a /usr/local/lib
  - popd

script:
  - export CC=gcc-7
  - export CXX=g++-7
  - mkdir build
  - cd build
  - cmake ../
  - make
  - make test

notifications:
  email: false