matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
      env:
         - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"

before_install:
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 60 --slave /usr/bin/g++ g++ /usr/bin/g++-8
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 40 --slave /usr/bin/g++ g++ /usr/bin/g++-8
  - sudo update-alternatives --config gcc
  - eval "${MATRIX_EVAL}"

install:
  - mkdir ~/googletest
  - pushd ~/googletest
  - wget -qO - https://github.com/google/googletest/archive/release-1.8.0.tar.gz | tar -xz
  - cmake -D CMAKE_INSTALL_PREFIX:PATH=$HOME/googletest -D CMAKE_BUILD_TYPE=Release googletest-release-1.8.0
  - make install
  - popd

script:
  - mkdir build
  - cd build
  - cmake -D GTEST_ROOT:PATH=$HOME/googletest ..
  - make
  - make test

notifications:
  email: false